# coding: utf-8

"""
    Permify API

    Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

    The version of the OpenAPI document: v1.6.1
    Contact: hello@permify.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from permify.models.component import Component

class TestComponent(unittest.TestCase):
    """Component unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponent(self):
        """Test Component"""
        # inst = Component()

if __name__ == '__main__':
    unittest.main()
