# coding: utf-8

"""
    Permify API

    Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

    The version of the OpenAPI document: v1.4.2
    Contact: hello@permify.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from permify.models.data_change_operation import DataChangeOperation

class TestDataChangeOperation(unittest.TestCase):
    """DataChangeOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataChangeOperation(self):
        """Test DataChangeOperation"""
        # inst = DataChangeOperation()

if __name__ == '__main__':
    unittest.main()
