# coding: utf-8

"""
    Permify API

    Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

    The version of the OpenAPI document: v0.7.7
    Contact: hello@permify.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.entity_definition import EntityDefinition

class TestEntityDefinition(unittest.TestCase):
    """EntityDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityDefinition:
        """Test EntityDefinition
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityDefinition`
        """
        model = EntityDefinition()
        if include_optional:
            return EntityDefinition(
                name = '',
                relations = {
                    'key' : openapi_client.models.relation_definition.RelationDefinition(
                        name = '', 
                        relation_references = [
                            openapi_client.models.relation_reference.RelationReference(
                                type = '', 
                                relation = '', )
                            ], )
                    },
                permissions = {
                    'key' : openapi_client.models.permission_definition.PermissionDefinition(
                        name = '', 
                        child = openapi_client.models.child.Child(
                            leaf = openapi_client.models.leaf.Leaf(
                                computed_user_set = openapi_client.models.computed_user_set.ComputedUserSet(
                                    relation = '', ), 
                                tuple_to_user_set = openapi_client.models.tuple_to_user_set.TupleToUserSet(
                                    tuple_set = openapi_client.models.tuple_set.TupleSet(
                                        relation = '', ), 
                                    computed = openapi_client.models.computed_user_set.ComputedUserSet(
                                        relation = '', ), ), 
                                computed_attribute = openapi_client.models.computed_attribute.ComputedAttribute(
                                    name = '', ), 
                                call = openapi_client.models.v1/call.v1.Call(
                                    rule_name = '', 
                                    arguments = [
                                        openapi_client.models.argument.Argument(
                                            context_attribute = openapi_client.models.context_attribute.ContextAttribute(
                                                name = '', ), )
                                        ], ), ), 
                            rewrite = openapi_client.models.rewrite.Rewrite(
                                rewrite_operation = 'OPERATION_UNSPECIFIED', 
                                children = [
                                    openapi_client.models.child.Child()
                                    ], ), ), )
                    },
                attributes = {
                    'key' : openapi_client.models.attribute_definition.AttributeDefinition(
                        name = '', 
                        type = 'ATTRIBUTE_TYPE_UNSPECIFIED', )
                    },
                references = {
                    'key' : 'REFERENCE_UNSPECIFIED'
                    }
            )
        else:
            return EntityDefinition(
        )
        """

    def testEntityDefinition(self):
        """Test EntityDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
