# coding: utf-8

"""
    Permify API

    Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

    The version of the OpenAPI document: v1.4.2
    Contact: hello@permify.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from permify.models.permission_check_response_metadata import PermissionCheckResponseMetadata

class TestPermissionCheckResponseMetadata(unittest.TestCase):
    """PermissionCheckResponseMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionCheckResponseMetadata:
        """Test PermissionCheckResponseMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionCheckResponseMetadata`
        """
        model = PermissionCheckResponseMetadata()
        if include_optional:
            return PermissionCheckResponseMetadata(
                check_count = 56
            )
        else:
            return PermissionCheckResponseMetadata(
        )
        """

    def testPermissionCheckResponseMetadata(self):
        """Test PermissionCheckResponseMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
