# coding: utf-8

"""
    Permify API

    Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

    The version of the OpenAPI document: v1.4.2
    Contact: hello@permify.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from permify.models.well_known_type import WellKnownType

class TestWellKnownType(unittest.TestCase):
    """WellKnownType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWellKnownType(self):
        """Test WellKnownType"""
        # inst = WellKnownType()

if __name__ == '__main__':
    unittest.main()
