# coding: utf-8

"""
    Permify API

    Permify is an open source authorization service for creating fine-grained and scalable authorization systems.

    The version of the OpenAPI document: v1.4.2
    Contact: hello@permify.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from permify.models.argument import Argument
from permify.models.context import Context
from permify.models.entity import Entity
from permify.models.permission_check_request_metadata import PermissionCheckRequestMetadata
from permify.models.subject import Subject
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CheckBody(BaseModel):
    """
    PermissionCheckRequest is the request message for the Check method in the Permission service.
    """ # noqa: E501
    metadata: Optional[PermissionCheckRequestMetadata] = None
    entity: Optional[Entity] = None
    permission: Optional[StrictStr] = Field(default=None, description="The action the user wants to perform on the resource")
    subject: Optional[Subject] = None
    context: Optional[Context] = None
    arguments: Optional[List[Argument]] = Field(default=None, description="Additional arguments associated with this request.")
    __properties: ClassVar[List[str]] = ["metadata", "entity", "permission", "subject", "context", "arguments"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CheckBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of entity
        if self.entity:
            _dict['entity'] = self.entity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subject
        if self.subject:
            _dict['subject'] = self.subject.to_dict()
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['context'] = self.context.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in arguments (list)
        _items = []
        if self.arguments:
            for _item in self.arguments:
                if _item:
                    _items.append(_item.to_dict())
            _dict['arguments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CheckBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metadata": PermissionCheckRequestMetadata.from_dict(obj.get("metadata")) if obj.get("metadata") is not None else None,
            "entity": Entity.from_dict(obj.get("entity")) if obj.get("entity") is not None else None,
            "permission": obj.get("permission"),
            "subject": Subject.from_dict(obj.get("subject")) if obj.get("subject") is not None else None,
            "context": Context.from_dict(obj.get("context")) if obj.get("context") is not None else None,
            "arguments": [Argument.from_dict(_item) for _item in obj.get("arguments")] if obj.get("arguments") is not None else None
        })
        return _obj


