name: Auto Release on 'new-release' commit

on:
  push:
    branches:
      - main
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Check commit message for '#new-release'
        run: |
          if git log --format=%B -n 1 $GITHUB_SHA | grep -q '#new-release'; then
            latest_release=$(git describe --tags --abbrev=0)            
            new_release=$(echo $latest_release | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
            echo "Creating release $new_release"
            git tag -a $new_release -m "Release $new_release"
            git push origin $new_release
          else
            echo "Commit does not include '#new-release'. Skipping release."
            exit 0
          fi