name: Auto Release on '#new-release' commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Check commit message for '#new-release'
        id: check_message
        run: |
          if git log --format=%B -n 1 | grep -q '#new-release'; then
            latest_release=$(git describe --tags --always --abbrev=0)            
            new_release=$(echo $latest_release | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
            echo "Creating release $new_release"
            git tag -a $new_release -m "Release $new_release"
            git push origin $new_release
            echo "::set-output name=new_release::$new_release"
          else
            echo "Commit does not include '#new-release'. Skipping release."
            exit 0
          fi

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          tag="${{ steps.check_message.outputs.new_release }}"
          title="${tag#v}"
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$title" \
              --generate-notes
